version: "3"

dotenv: [".env"]

tasks:
  run-tool:
    - go run cmd/go-agent/main.go -task "what is the weather in Tokio?"

  run-prompt:
   -  go run cmd/go-agent/main.go -task "tell a joke"

  lint:
    - golangci-lint fmt
    - golangci-lint run --enable-only tagalign,whitespace,nlreturn --fix
    - golangci-lint run

  test:
    - go test ./... -v
