// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/paveldroo/go-agent/client"
	"github.com/paveldroo/go-agent/tool/tool"
	mock "github.com/stretchr/testify/mock"
)

// NewLLMClient creates a new instance of LLMClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLLMClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *LLMClient {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &LLMClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// LLMClient is an autogenerated mock type for the LLMClient type
type LLMClient struct {
	mock.Mock
}

type LLMClient_Expecter struct {
	mock *mock.Mock
}

func (_m *LLMClient) EXPECT() *LLMClient_Expecter {
	return &LLMClient_Expecter{mock: &_m.Mock}
}

// Request provides a mock function for the type LLMClient
func (_mock *LLMClient) Request(context1 context.Context, messages []client.Message) (client.ChatResponse, error) {
	ret := _mock.Called(context1, messages)

	if len(ret) == 0 {
		panic("no return value specified for Request")
	}

	var r0 client.ChatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []client.Message) (client.ChatResponse, error)); ok {
		return returnFunc(context1, messages)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []client.Message) client.ChatResponse); ok {
		r0 = returnFunc(context1, messages)
	} else {
		r0 = ret.Get(0).(client.ChatResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []client.Message) error); ok {
		r1 = returnFunc(context1, messages)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LLMClient_Request_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Request'
type LLMClient_Request_Call struct {
	*mock.Call
}

// Request is a helper method to define mock.On call
//   - context1 context.Context
//   - messages []client.Message
func (_e *LLMClient_Expecter) Request(context1 any, messages any) *LLMClient_Request_Call {
	return &LLMClient_Request_Call{Call: _e.mock.On("Request", context1, messages)}
}

func (_c *LLMClient_Request_Call) Run(run func(context1 context.Context, messages []client.Message)) *LLMClient_Request_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []client.Message
		if args[1] != nil {
			arg1 = args[1].([]client.Message)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *LLMClient_Request_Call) Return(chatResponse client.ChatResponse, err error) *LLMClient_Request_Call {
	_c.Call.Return(chatResponse, err)
	return _c
}

func (_c *LLMClient_Request_Call) RunAndReturn(run func(context1 context.Context, messages []client.Message) (client.ChatResponse, error)) *LLMClient_Request_Call {
	_c.Call.Return(run)
	return _c
}

// Tools provides a mock function for the type LLMClient
func (_mock *LLMClient) Tools() []tool.Tool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Tools")
	}

	var r0 []tool.Tool
	if returnFunc, ok := ret.Get(0).(func() []tool.Tool); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tool.Tool)
		}
	}
	return r0
}

// LLMClient_Tools_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Tools'
type LLMClient_Tools_Call struct {
	*mock.Call
}

// Tools is a helper method to define mock.On call
func (_e *LLMClient_Expecter) Tools() *LLMClient_Tools_Call {
	return &LLMClient_Tools_Call{Call: _e.mock.On("Tools")}
}

func (_c *LLMClient_Tools_Call) Run(run func()) *LLMClient_Tools_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LLMClient_Tools_Call) Return(tools []tool.Tool) *LLMClient_Tools_Call {
	_c.Call.Return(tools)
	return _c
}

func (_c *LLMClient_Tools_Call) RunAndReturn(run func() []tool.Tool) *LLMClient_Tools_Call {
	_c.Call.Return(run)
	return _c
}
